services:
  mariadb:
    container_name: mariadb
    image: mariadb:11.2
    hostname: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-homestead}
      MYSQL_USER: ${MYSQL_USER:-countryadmin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-rock4me}
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - databases-network
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin -uroot -p${MYSQL_ROOT_PASSWORD:-secret} ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mariadb-data:

networks:
  databases-network:
    external: true
